from enum import Enum

from src.constants.score import Score


class Teacher(Enum):
    CARMEN_SALAS = ("CARMEN AMALIA SALAS BROWN", Score.GOOD)
    NORMA_SARMIENTO = ("NORMA CONSTANZA SARMIENTO BENAVIDES", Score.UNKNOWN)
    GERMAN_OBANDO = ("GERMAN DARIO OBANDO BRAVO", Score.UNKNOWN)
    CARLOS_ALVAREZ = ("CARLOS EDUARDO ALVAREZ CABRERA", Score.UNKNOWN)
    PEDRO_WIGHTMAN = ("PEDRO MARIO WIGHTMAN ROJAS", Score.UNKNOWN)
    DANIEL_BOJACA = ("DANIEL ALFONSO BOJACA TORRES", Score.UNKNOWN)
    GLORIA_GALLO = ("GLORIA AYDEE GALLO CUBILLOS", Score.UNKNOWN)
    ADRYAN_PINEDA = ("ADRYAN FABRIZIO PINEDA REPIZZO", Score.UNKNOWN)
    TIRSO_BUENO = ("TIRSO HERNAN BUENO CASTANEDA", Score.UNKNOWN)
    JESSICA_MURILLO = ("JESSICA MURILLO MENA", Score.UNKNOWN)
    HAROLD_VILLAMIL = ("HAROLD ALEXANDER VILLAMIL CASTILLO", Score.UNKNOWN)
    MARIA_LOPEZ = ("MARIA PAULA LOPEZ VELASQUEZ", Score.UNKNOWN)
    JHONATAN_DIAZ = ("JHONATAN JULIAN DIAZ TIMOTE", Score.UNKNOWN)
    MARIA_BATISTA = ("MARIA FERNANDA BATISTA MORALES", Score.UNKNOWN)

    MONITOR = ("MONITOR", Score.UNKNOWN)
    UNKNOWN = ("N/N", Score.UNKNOWN)

    def __init__(self, user_name: str, score: Score):
        self.user_name = user_name
        self.score = score
